version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - game-gallery
        container_name: game-gallery_nginx
    game-gallery:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: game-gallery
        working_dir: /var/www  # Це дозволяє запускати команди в робочій директорії Laravel
        command: bash -c "npm install && npm run dev && php-fpm"  # Спочатку встановлює npm залежності, потім запускає php-fpm
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db1:/var/lib/mysql
        environment:
            MYSQL_DATABASE: game-gallery
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8101:3306"
        container_name: game-gallery_db
